# NOTE: For maximum performance, build using a nightly compiler
# If you are using rust stable, remove the "-Zshare-generics=y" below.
[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[profile.release]
lto = "thin"

[build]
